n = input('Digite algo: ')
print('Vamos ver se este primeiro é um numero: ')
print(n.isnumeric())
print('Se é uma letra: ')
print(n.isalpha())
print('Se é um numero alfanumerico: ')
print(n.isalnum())
print('Se só tem letras maiusculas: ')
print(n.isupper())
print('Ou se só tem letras minusculas: ')
print(n.islower())
