n = input('Digite algo: ')
print('Estamos falando aqui de um', type(n))
print('Agora vamos anlisar mais um pouco o que você digitou: ')
print('Vamos ver se é um numero: ')
print(n.isnumeric())
print('Se é decimal: ')
print(n.isdecimal())
print('Uma letra: ')
print(n.isalpha())
print('Um alphanumerico: ')
print(n.isalnum())
print('Se está em caixa alta: ')
print(n.isupper())
print('Ou se está em minusculo: ')
print(n.islower())
