nome = input('Insira um nome: ')
nome_c = nome.strip()
print('Este é seu nome em maiusculo: {}'.format(nome_c.upper()))
print('Este é seu nome em minusculo: {}'.format(nome_c.lower()))
numero_de_letras_nome = (len(nome_c) - nome_c.count(' '))
print('Seu nome tem ao todo {} letras'.format(numero_de_letras_nome))
nome1 = nome_c.split()
nome2 = len(nome1[0])
print('Seu primeiro nome tem {} letras'.format(nome2))
