dia = input('qual é o dia do seu nascimento? ')
mês = input('qual é o mês do seu nascimento? ')
ano = input('qual é o ano do seu nascimento? ')
print('você nasceu no dia', dia, 'do mês de', mês, 'no ano de', ano)
print('========')
dia = input('qual é o dia do seu nascimento? ')
mês = input('qual é o mês do seu nascimento? ')
ano = input('qual é o ano do seu nascimento? ')
print('você nasceu no dia', dia, 'de', mês, 'de',ano, '. Correto?')
